name: Load Raw Data like artifact to wandb

on:
  push:
    branches:
      - main
    paths:
      - 'src/data/load.py'

jobs:
  load_data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install dependencies
      run: |
        echo "Instalando dependencias..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install scikit-learn  # Agrega la instalaci贸n de scikit-learn
        echo "Instalaci贸n de dependencias completa."
    - name: Login to WandB
      run: |
        echo "Iniciando sesi贸n en WandB..."
        wandb login ${{ secrets.WANDB_API_KEY }}
        echo "Inicio de sesi贸n exitoso."
    - name: Run load.py
      run: |
        echo "Ejecutando load.py..."
        python src/data/load.py --IdExecution ${{ github.run_number }}
